name: NodeJS Pipeline

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Use Expo 3.x
        uses: expo/expo-github-action@v5
        with:
          expo-version: 3.x

      - name: Instal dependencies
        run: yarn install

      - name: Build web
        run: yarn build:web

      - name: Archive build web artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-web
          path: build-web
